### ISSUE TITLE
Bad merge in NotificationSystem

### ISSUE THREAD

**Issue by dthaler** [orcasound/aifororcas-livesystem#351]
https://github.com/orcasound/aifororcas-livesystem/actions/runs/19103681711 hit a build error:
> Error: /home/runner/work/aifororcas-livesystem/aifororcas-livesystem/NotificationSystem/NotificationSystem/SendSubscriberEmail.cs(41,35): error CS7036: There is no argument given that corresponds to the required parameter 'configuration' of 'OrcasiteHelper.InitializeAsync(IConfiguration)' [/home/runner/work/aifororcas-livesystem/aifororcas-livesystem/NotificationSystem/NotificationSystem/NotificationSystem.csproj]
